server:
  port: 9091

spring:
  application:
    name: msvc-autenticacion

  
  datasource:
    url: jdbc:postgresql://postgres16:5432/msvc-autenticacion
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  graphql:
    graphiql:
      enabled: true
    path: /graphql


app:
  jwt:
    secret: secretSuperSeguroDe256BitsParaHMACSHA
    expiration: 86400000
