eureka:
  client:
    register-with-eureka: false


spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: msvc-autenticacion
          uri: http://localhost:8081
          predicates:
            - Path=/graphql/**
          filters:
            - AddRequestHeader=Content-Type, application/json
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:8080"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600