spring:
  application:
    name: msvc-eureka
server:
  port: 8761

eureka:
  instance:
    hostname: msvc-eureka
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://msvc-eureka:8761/eureka/
  server:
    enableSelfPreservation: false
    waitTimeInMsWhenSyncEmpty: 0
