server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configuraciones
        fail-fast: true
      discovery:
        enabled: false
      loadbalancer:
        retry:
          enabled: true